schema_version = 1
name = "default-launcher-icons"

[items."builtin.command-line"]
label = "Command Line"
image = "launcher_icons/command_line.png"
lines = [
  ' ______ ',
  '|cmd>  |',
  '|      |',
  '|______|',
]

[items."builtin.editor"]
label = "Editor"
image = "launcher_icons/editor.png"
lines = [
  ' _____ ',
  '|==  |',
  '|  __|',
  '|_/__|',
]
