name: Linux

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install stable Rust
        run: rustup toolchain install stable --profile minimal && rustup default stable
      - name: Build
        run: cargo build --workspace --locked
      - name: Test
        run: cargo test --workspace --locked
